### ISSUE TITLE
discrepancy between stored values and calculated values

### ISSUE THREAD

**Issue by ryants** [LoLab-VU/PyDREAM#5]
After I run PyDREAM and output the parameters and log-posteriors to a .npy file, I load the .npy files assuming that entry _i_ of the parameter file corresponds to entry _i_ of the log-posteriors file.  However when I recalculate the log-posterior value manually, the values are different (often by multiple orders of magnitude).  

From the files I have, the entries in the parameter file correspond to the log-posterior file are consistent up to some arbitrary point (i.e. I can successfully recaculate the posterior), when they become inconsistent (i.e. the log-likelihood blows up).

Any ideas what may be happening?  My model (written in PySB) and PyDREAM file are attached.

[rab_dream.zip](https://github.com/LoLab-VU/PyDREAM/files/1744835/rab_dream.zip)

I'm using Python 3.6 on a Linux workstation and the master branches of PySB and PyDREAM (as of about two weeks ago)

**Comment by ryants** [comment]
This may actually be a PySB issue.  Haven't fully sorted it out yet

**Comment by eshockley** [comment]
FWIW, I haven't been able to replicate this problem with a test model or with the model you provided (I don't have your experimental data of course, so I'm using random noise around a random simulation, but otherwise I didn't change anything) yet, out to ~5000 iterations.  

Just to double check, could you confirm that you're looking at the log posterior, and not just the log likelihood? With a defined parameter vector and likelihood function, you can calculate the log posterior at a particular point like so:
`from pydream.model import Model
model = Model(likelihood=likelihood_bng, sampled_parameters=parameter_vector)
logp = np.sum(model.total_logp(paramset))`
`model.total_logp()` returns a vector of the log prior and the log likelihood for a given parameter vector, and so far the output files I've checked have had logps that matched the saved values when recalculated.

**Comment by ryants** [comment]
I had been considering the prior (always a constant since all parameters had uniform priors) in the recalculations.  I haven't been having this issue since switching to scipy integrators... I'll revisit and close the issue for now.
